#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

for my $event_conf (qw (nethserver-phpmyadmin-update))
{
    event_actions($event_conf, 
             'initialize-default-databases' => '00',
             'nethserver-phpmyadmin-mysqlsettings' => '01',
             'nethserver-phpmyadmin-conf' => '02');
}

for my $event (qw(
    nethserver-phpmyadmin-update 
    nethserver-phpmyadmin-save 

    ))
{
    templates2events("/etc/phpMyAdmin/config.inc.php", $event);
    templates2events("/etc/httpd/conf.d/phpMyAdmin.conf", $event);
    templates2events("/etc/httpd/conf/httpd.conf", $event);
    event_services($event, qw(httpd reload));
}

