#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

for my $event (qw(
    nethserver-phpmyadmin-update 
    nethserver-phpmyadmin-save 

    ))
{
    templates2events("/etc/phpMyAdmin/config.inc.php", $event);
    templates2events("/etc/httpd/conf.d/phpMyAdmin.conf", $event);
    templates2events("/etc/httpd/conf/httpd.conf", $event);
    event_services($event, qw(httpd reload));
}
