#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package esmith;

use strict;
use Errno;
use esmith::util;
#use NethServer::Password;


  my $password = esmith::util::genRandomPassword('/etc/my.pwd')
        || die('Could not retrieve mysql password!');

my $commands = join("\n", 
        "DROP USER 'admin'\@'localhost';",
        "CREATE USER 'admin'\@'localhost' IDENTIFIED BY '$password';",
        "GRANT ALL PRIVILEGES ON *.* TO 'admin'\@'localhost' WITH GRANT OPTION;") . "\n";

print $commands;

open(FH, '|-', '/usr/bin/mysql -B -f') || die("[ERROR] Could not connect to mysql");
print FH $commands;     
close(FH);

exit (0);
