#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use NethServer::Password;
exit(0) unless system('/usr/bin/mysql phpmyadmin  -e "describe pma_userconfig" &> /dev/null') != 0;

### Creation of the mysql base for phpmyadmin

# creation of a password
  my $pass = NethServer::Password::store('phpmyadmin') || die('Could not generate phpmyadmin password!');

#mysql works
  my $commands = join("\n",
                 "GRANT ALL PRIVILEGES ON `phpmyadmin`.* TO 'phpmyadmin'\@'localhost' IDENTIFIED BY '$pass';",
                 "FLUSH PRIVILEGES;",
                 "CREATE DATABASE IF NOT EXISTS phpmyadmin DEFAULT CHARACTER SET = 'utf8';",
                 "USE mysql;",
                 "REPLACE INTO user (host,user,password) VALUES ('localhost','phpmyadmin', PASSWORD ('$pass'));",
                 "REPLACE INTO db (host,db,user,select_priv, insert_priv, update_priv, delete_priv,create_priv, 
                     alter_priv, index_priv, drop_priv, create_tmp_table_priv,grant_priv, 
                     lock_tables_priv, references_priv) 
                  VALUES ( 'localhost','phpmyadmin','phpmyadmin','Y', 'Y', 'Y', 'Y','Y', 'Y', 'Y', 'Y', 'Y','N', 'Y', 'Y');"
) . "\n";

   print $commands;
   open(FH, '|-', '/usr/bin/mysql -B -f') || die("[ERROR] Could not connect to mysql");
   print FH $commands;
   close(FH);

# import the phpmyadmin sql structure
   my $dbstruct = `rpm -qd nethserver-phpmyadmin | grep phpmyadmin.sql`;
   system ("/usr/bin/mysql phpmyadmin < $dbstruct");

