#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package esmith;

use strict;
use Errno;
use NethServer::Password;
### Creation of the user Admin with all permissions

  my $password = NethServer::Password::store('mysql')
        || die('Could not retrieve mysql password!');
  my $admin_condition = `/usr/bin/mysql -e " SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = 'admin');"`;

if ($admin_condition =~ '0')

    {
    my $commands = join("\n",
        "GRANT ALL PRIVILEGES ON *.* TO 'admin'\@'localhost' IDENTIFIED BY '$password' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0
         MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;") . "\n";
    print $commands;

    open(FH, '|-', '/usr/bin/mysql -B -f') || die("[ERROR] Could not connect to mysql");
    print FH $commands;
    close(FH);
    }

exit (0);
